#+TITLE:     Using Cellular Automata for Data Mining
#+AUTHOR:    James Hurford
#+EMAIL:     
#+DATE:      
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 


* Introduction
  A cellular automata system is a collection of cells arranged in a
  grid.  Each cell has a value associated with it, and these values
  are called states.  The state is a set of finite values.  When first
  set up the cellular automata is seeded with states for each cell,
  which could be randomly assigned or not. The cellular automata is
  then put through a series of steps, and at each step the states of
  each cell is updated according to some simple rules based on the
  values of each its immediate neighbours.  There are two popular
  neighbourhoods, the Von Neumann and Moore neighbourhoods.  Von
  Neumann method uses only the north, south, east and west neighbours
  and Moore

  
* Background
  
* Data Mining (Clustering)
  
* Results
  
* Conclusions
  

* References

\bibliographystyle{plain}
\bibliography{bibliography}
