CC=g++
CXX=g++

CFLAGS=-pedantic -ansi -Wall
CXXFLAGS=$(CFLAGS)

OBJECTS=cellular-automata.o cell.o graph.o


all: main

main: $(OBJECTS)
#	g++ -o cellula-automata $(OBJECTS)

clean:
	$(RM) $(OBJECTS)